project:
  type: book
  output-dir: _book
  resources:
    - OV1114-Node-Notes.pdf
    - OV1114-Node-Notes.docx

book:
  title: "OV1114 Node Notes"
  author: "Benjamin Evans"
  date: last-modified
  downloads: [pdf, docx]
  repo-url: https://github.com/3enji/EDM124_quanto_test
  repo-actions: [source] #[source, issue, edit]
  reader-mode: true
  chapters:
    - index.qmd
    - node_01.qmd
    - node_02.qmd
    - node_03.qmd
    - node_04.qmd
    - node_05.qmd
    - node_06.qmd
    - node_07.qmd
    - node_08.qmd
    - node_09.qmd
    - node_xx.qmd
    # - part: "Electromagnetic Spectrum"
    #   chapters:
    #   - node_02.qmd
    #   - node_03.qmd
    # - part: "Geometrical Optics"
    #   chapters:
    #   - node_04.qmd
    #   - node_05.qmd
    #   - node_06.qmd
    #   - node_07.qmd
    # - part: "Wave Optics"
    #   chapters:
    #   - node_08.qmd
    #   - node_09.qmd
    # - part: "Physics of the Eye"
    #   chapters:
    #   - node_10.qmd
    #   - node_11.qmd
    # - part: "Colour"
    #   chapters:
    #   - node_12.qmd
    #   - node_13.qmd
    #   - node_14.qmd
    #   - node_15.qmd
    #   - node_16.qmd
    #   - node_17.qmd
    # - part: "Measuring Light"
    #   chapters:
    #   - node_18.qmd
    #   - node_19.qmd
    #   - node_20.qmd
    # - part: "Appendices"
    #   chapters:
    #   - node_xx.qmd

format:
  html:
    highlight-style: a11y
    theme: 
      light: flatly #cosmo, materia, simplex, flatly, a11y
      dark: darkly #darkly, solar, slate
    code-fold: true
    code-tools: true
    toc: true
    # respect-user-color-scheme: true
    number-sections: true
    equation-numbering: true  # enables auto equation numbers
    fig-cap-location: bottom  # or top
    html-math-method: mathjax
    # fontsize: 1.1em
    css: 
      - include/webex.css
      - styles.css
    include-after-body: 
      include/webex.js
    categories:
      - EDM124
      - ITO
      - OV1114
      - 2025-26
    # include-in-header:
      # text: |
      #   <button id="fontToggle">Toggle Font</button>
      #   <script>
      #     const toggleBtn = document.getElementById("fontToggle");
      #     const currentFont = localStorage.getItem("fontStyle") || "sans-serif";
      #     document.body.classList.add(currentFont);

      #     toggleBtn.onclick = () => {
      #       const isSans = document.body.classList.contains("sans-serif");
      #       document.body.classList.remove("sans-serif", "serif");
      #       const newFont = isSans ? "serif" : "sans-serif";
      #       document.body.classList.add(newFont);
      #       localStorage.setItem("fontStyle", newFont);
      #     };
      #   </script>
  pdf:
    pdf-engine: xelatex   # or lualatex / pdflatex
    # mainfont: "Open Sans"
    # monofont: "Roboto Mono"
    include-in-header: preamble.tex
  docx:
    default
